# Site settings
title: Ducky Zhou 的个人主页
email: your-email@example.com
description: "我是 Ducky Zhou，一名新生，我的计算机科学之路。"

# Base URL (如果使用自定义域名则留空)
baseurl: "" 
url: "https://ducky-zhou.github.io" 

# Build settings
# 使用 GitHub Pages 官方支持的 theme
theme: minima
plugins:
  - jekyll-feed
  
  
  
  Add minima theme config
