# Site settings
title: Ducky Zhou 的个人主页
email: ducky_zhou@outlook.com ducky.zhou.zxy@gmail.com 3250105688@zju.edu.cn
description: "Freshman Logs: My Computer Science Journey @ ZJU （My personal repository~）"

# Base URL (如果使用自定义域名则留空)
baseurl: "" 
url: "https://ducky-zhou.github.io" 

# Build settings
# 使用 GitHub Pages 官方支持的 theme
theme: minima
plugins:
  - jekyll-feed
